import { Keypair, PublicKey, TransactionBuilder, createAccount, createRialoClient, RIALO_TESTNET_CHAIN, SYSTEM_PROGRAM_ID } from '@rialo/ts-cdk';
import { encodeAddLiquidity, encodeBuy, encodeGraduate, encodeInitializeAndBuy, encodeRemoveLiquidity, encodeSell } from './rialofunInstruction.js';

export const SETTLEMENT_PROGRAM = '2iquqTG5Frnj64kzwa5RFWawuJpXg3fYhMkTPiT22AiM';
export const TOKEN_PROGRAM = 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
export const LIVE_MARKET = Object.freeze({ program:'6QeXFSGKEjnBGudkGfT9qP7tShdFVE8mLgztSZnP747k', state:'81wYYujgN2abqzP5dPGvpsYGV9ZYUPgwTeAcarrYnDR6', mint:'FXmAAyqRwdyvBgmG5KY1CVRVeQpb6kxQzjDbHkRXoc8d', tokenAccount:'4mG2k1hdLWQ3My6WuerifR53zfukVzpBFmEMFtEa3bNz' });
export const GRADUATION_MARKET = Object.freeze({ program:SETTLEMENT_PROGRAM, state:'59acQBag2qNh9RSLQ47uDXAwxQpSvcC4YHVUsNRbpf68', mint:'HD7iYzPWFD2JeGjC8P3nbkcLveHq8wYBAg6geQzjHg9M', tokenAccount:'6iUd4kBUonuSVjjvH7R6Nj8AnUEcMxyikUriPrTwPchr' });
const client=createRialoClient({chain:RIALO_TESTNET_CHAIN}); const program=PublicKey.fromString(SETTLEMENT_PROGRAM); const tokenProgram=PublicKey.fromString(TOKEN_PROGRAM); const systemProgram=PublicKey.fromString(SYSTEM_PROGRAM_ID);
const initAccountData=owner=>{const d=new Uint8Array(33);d[0]=18;d.set(owner.toBytes(),1);return d};
const metas=(state,trader,mint,token,authority)=>[{pubkey:state,isSigner:false,isWritable:true},{pubkey:trader,isSigner:true,isWritable:true},{pubkey:mint,isSigner:false,isWritable:true},{pubkey:token,isSigner:false,isWritable:true},{pubkey:authority,isSigner:false,isWritable:false},{pubkey:tokenProgram,isSigner:false,isWritable:false},{pubkey:systemProgram,isSigner:false,isWritable:false}];
const storageKey=(wallet,mint)=>`rialofun:token-account:${wallet}:${mint}`;
const registryKey='rialofun:onchain-markets:v1';
const historyKey='rialofun:confirmed-trades:v1';
const validMarket=value=>value&&typeof value==='object'&&typeof value.id==='string'&&typeof value.name==='string'&&typeof value.ticker==='string'&&value.onchain&&typeof value.onchain.state==='string'&&typeof value.onchain.mint==='string';
export function loadOnchainMarkets(){try{const parsed=JSON.parse(localStorage.getItem(registryKey)||'[]');return Array.isArray(parsed)?parsed.filter(validMarket):[]}catch{return[]}}
export function saveOnchainMarket(market){const image=typeof market.image==='string'&&(market.image.startsWith('data:')||market.image.startsWith('/api/images/tokens/'))?market.image:'';const safe={id:market.id,name:market.name,ticker:market.ticker,creator:market.creator,image,createdAt:market.createdAt,onchain:market.onchain};const existing=loadOnchainMarkets().filter(item=>item.id!==safe.id);localStorage.setItem(registryKey,JSON.stringify([safe,...existing].slice(0,100)));}
export function loadTradeHistory(marketId){try{return JSON.parse(localStorage.getItem(historyKey)||'[]').filter(item=>item.marketId===marketId)}catch{return[]}}
function recordTrade(entry){const history=(()=>{try{return JSON.parse(localStorage.getItem(historyKey)||'[]')}catch{return[]}})();const previous=history.find(item=>item.signature===entry.signature)||{};const merged={...previous,...entry};localStorage.setItem(historyKey,JSON.stringify([merged,...history.filter(item=>item.signature!==entry.signature)].slice(0,500)));}
export function recordConfirmedTrade(entry){recordTrade(entry)}
export async function discoverOnchainMarkets(){const [entries]=await client.getAccountsByOwner(program);const saved=loadOnchainMarkets();return entries.filter(entry=>entry.account?.data?.[1]==='base64'&&entry.account.data[0]).flatMap(entry=>{const bytes=Uint8Array.from(atob(entry.account.data[0]),c=>c.charCodeAt(0));if(bytes.length!==128||bytes[0]!==1)return[];const state=entry.pubkey,mint=PublicKey.fromBytes(bytes.slice(8,40)).toString(),known=saved.find(item=>item.onchain?.state===state);return[{...createDiscoveredMarket(known,state,mint),onchain:{...(known?.onchain||{}),program:known?.onchain?.program||SETTLEMENT_PROGRAM,state,mint}}]})}
function createDiscoveredMarket(known,state,mint){return known||{id:`chain-${state.slice(0,8)}`,name:'RialoFun market',ticker:`RLO-${mint.slice(0,4)}`,creator:'On-chain',image:'',createdAt:Date.now()}}

async function walletSend(wallet,tx,summary,extraSigners=[]){
  if(extraSigners.length)tx.signAll(extraSigners); const feature=window.rialoTestnetWallet?.features?.['rialo:signTransaction']; if(!feature)throw new Error('Wallet signing feature is unavailable.');
  const approval=feature.signTransaction({transaction:tx.serialize(),summary});
  const timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error('Wallet approval timed out. Open the Rialo Wallet extension and approve the pending request.')),45000));
  const {signedTransaction}=await Promise.race([approval,timeout]); const result=await client.sendAndConfirmTransaction(signedTransaction);
  if(!result.executed)throw new Error(`Transaction reverted: ${JSON.stringify(result.err)}`); return result.signature;
}
const builder=async payer=>TransactionBuilder.create().setPayer(payer).setValidFrom(BigInt(Date.now())).setConfigHashPrefix(await client.getConfigHashPrefix());
async function ensureTokenAccount(wallet,mint,b,preferred){
  const saved=localStorage.getItem(storageKey(wallet.toString(),mint.toString())); if(saved){try{await client.getAccountInfo(PublicKey.fromString(saved));return{address:PublicKey.fromString(saved),signer:null}}catch{localStorage.removeItem(storageKey(wallet.toString(),mint.toString()))}}
  if(preferred)try{const preferredKey=PublicKey.fromString(preferred),account=await client.getAccountInfo(preferredKey),bytes=Uint8Array.from(atob(account.data[0]),c=>c.charCodeAt(0));if(bytes.slice(32,64).every((value,index)=>value===wallet.toBytes()[index]))return{address:preferredKey,signer:null}}catch{}
  const signer=Keypair.generate(),rent=await client.getMinimumBalanceForRentExemption(165n); b.addInstruction(createAccount(wallet,signer.publicKey,rent,165n,tokenProgram)).addInstruction({programId:tokenProgram,accounts:[{pubkey:signer.publicKey,isSigner:false,isWritable:true},{pubkey:mint,isSigner:false,isWritable:false}],data:initAccountData(wallet)}); return{address:signer.publicKey,signer};
}
export async function tradeOnchain({walletAddress,market,side,amount,minOut}){
  const wallet=PublicKey.fromString(walletAddress),state=PublicKey.fromString(market.state),mint=PublicKey.fromString(market.mint),marketProgram=PublicKey.fromString(market.program||SETTLEMENT_PROGRAM); const b=await builder(wallet); const token=await ensureTokenAccount(wallet,mint,b,market.tokenAccount); const [authority]=PublicKey.findProgramAddress(['authority',state.toBytes()],marketProgram);
  const data=side==='buy'?encodeBuy({rloIn:amount,minTokensOut:minOut}):encodeSell({tokensIn:amount,minRloOut:minOut}); b.addInstruction({programId:marketProgram,accounts:metas(state,wallet,mint,token.address,authority),data});
  const signature=await walletSend(wallet,b.build(),{title:`${side==='buy'?'Buy':'Sell'} ${market.ticker}`,detail:`RialoFun Token-2022 settlement`,rloDelta:side==='buy'?`-${amount} RLO`:`+ at least ${minOut} RLO`},token.signer?[token.signer]:[]);
  if(token.signer){localStorage.setItem(storageKey(wallet.toString(),mint.toString()),token.address.toString());token.signer.dispose()} recordTrade({marketId:market.id||market.state,signature,side:side.toUpperCase(),account:wallet.toString(),rloAmount:amount,tokenAmount:null,time:Date.now()});return{signature,tokenAccount:token.address.toString()};
}
export async function launchOnchain({walletAddress,name,ticker,initialBuy,minTokensOut}){
  const wallet=PublicKey.fromString(walletAddress),state=Keypair.generate(),mint=Keypair.generate(),token=Keypair.generate(); const [authority]=PublicKey.findProgramAddress(['authority',state.publicKey.toBytes()],program); const [tombstone]=PublicKey.findProgramAddress(['mint_tombstone',mint.publicKey.toBytes()],tokenProgram); const b=await builder(wallet);
  const [sr,mr,tr]=await Promise.all([128n,82n,165n].map(n=>client.getMinimumBalanceForRentExemption(n))); b.addInstruction(createAccount(wallet,state.publicKey,sr,128n,program)).addInstruction(createAccount(wallet,mint.publicKey,mr,82n,tokenProgram)).addInstruction(createAccount(wallet,token.publicKey,tr,165n,tokenProgram));
  const im=new Uint8Array(35);im[0]=20;im[1]=6;im.set(authority.toBytes(),2); b.addInstruction({programId:tokenProgram,accounts:[{pubkey:mint.publicKey,isSigner:false,isWritable:true},{pubkey:tombstone,isSigner:false,isWritable:false}],data:im}).addInstruction({programId:tokenProgram,accounts:[{pubkey:token.publicKey,isSigner:false,isWritable:true},{pubkey:mint.publicKey,isSigner:false,isWritable:false}],data:initAccountData(wallet)}).addInstruction({programId:program,accounts:metas(state.publicKey,wallet,mint.publicKey,token.publicKey,authority),data:encodeInitializeAndBuy({initialBuyRlo:initialBuy,minTokensOut})});
  const signature=await walletSend(wallet,b.build(),{title:`Launch ${ticker}`,detail:`Create ${name}, Token-2022 mint and first curve buy`,rloDelta:`-${initialBuy} RLO`},[state,mint,token]); const market={program:SETTLEMENT_PROGRAM,state:state.publicKey.toString(),mint:mint.publicKey.toString(),tokenAccount:token.publicKey.toString()}; localStorage.setItem(storageKey(wallet.toString(),market.mint),market.tokenAccount); state.dispose();mint.dispose();token.dispose();return{signature,...market};
}
export async function graduateOnchain({ walletAddress, market }) {
  const wallet=PublicKey.fromString(walletAddress), state=PublicKey.fromString(market.state), mint=PublicKey.fromString(market.mint), marketProgram=PublicKey.fromString(market.program||SETTLEMENT_PROGRAM);
  const pool=Keypair.generate(), vault=Keypair.generate(), lpMint=Keypair.generate(), creatorLp=Keypair.generate(); const b=await builder(wallet);
  const [curveAuthority]=PublicKey.findProgramAddress(['authority',state.toBytes()],marketProgram); const [poolAuthority]=PublicKey.findProgramAddress(['pool_authority',pool.publicKey.toBytes()],marketProgram); const [mintTombstone]=PublicKey.findProgramAddress(['mint_tombstone',lpMint.publicKey.toBytes()],tokenProgram);
  const [poolRent,mintRent,tokenRent]=await Promise.all([192n,82n,165n].map(n=>client.getMinimumBalanceForRentExemption(n)));
  const initMint=new Uint8Array(35);initMint[0]=20;initMint[1]=6;initMint.set(poolAuthority.toBytes(),2); const initVault=initAccountData(poolAuthority); const initCreatorLp=initAccountData(wallet);
  b.addInstruction(createAccount(wallet,pool.publicKey,poolRent,192n,marketProgram)).addInstruction(createAccount(wallet,vault.publicKey,tokenRent,165n,tokenProgram)).addInstruction(createAccount(wallet,lpMint.publicKey,mintRent,82n,tokenProgram)).addInstruction(createAccount(wallet,creatorLp.publicKey,tokenRent,165n,tokenProgram));
  b.addInstruction({programId:tokenProgram,accounts:[{pubkey:lpMint.publicKey,isSigner:false,isWritable:true},{pubkey:mintTombstone,isSigner:false,isWritable:false}],data:initMint}).addInstruction({programId:tokenProgram,accounts:[{pubkey:vault.publicKey,isSigner:false,isWritable:true},{pubkey:mint,isSigner:false,isWritable:false}],data:initVault}).addInstruction({programId:tokenProgram,accounts:[{pubkey:creatorLp.publicKey,isSigner:false,isWritable:true},{pubkey:lpMint.publicKey,isSigner:false,isWritable:false}],data:initCreatorLp});
  b.addInstruction({programId:marketProgram,accounts:[{pubkey:state,isSigner:false,isWritable:true},{pubkey:curveAuthority,isSigner:false,isWritable:false},{pubkey:pool.publicKey,isSigner:false,isWritable:true},{pubkey:mint,isSigner:false,isWritable:true},{pubkey:vault.publicKey,isSigner:false,isWritable:true},{pubkey:lpMint.publicKey,isSigner:false,isWritable:true},{pubkey:poolAuthority,isSigner:false,isWritable:false},{pubkey:wallet,isSigner:true,isWritable:true},{pubkey:creatorLp.publicKey,isSigner:false,isWritable:true},{pubkey:tokenProgram,isSigner:false,isWritable:false},{pubkey:systemProgram,isSigner:false,isWritable:false}],data:encodeGraduate()});
  const signature=await walletSend(wallet,b.build(),{title:`Graduate ${market.ticker}`,detail:'Migrate bonding curve liquidity into a RialoFun DEX pool'},[pool,vault,lpMint,creatorLp]); const result={pool:pool.publicKey.toString(),vault:vault.publicKey.toString(),lpMint:lpMint.publicKey.toString(),creatorLp:creatorLp.publicKey.toString(),signature};[pool,vault,lpMint,creatorLp].forEach(key=>key.dispose());return result;
}
export async function liquidityOnchain({walletAddress,market,side,rloAmount,tokenAmount,lpAmount,minOut='0'}) {
  if(!market.pool) throw new Error('This market has not graduated to a DEX pool yet.');
  const wallet=PublicKey.fromString(walletAddress), state=PublicKey.fromString(market.state), mint=PublicKey.fromString(market.mint), programId=PublicKey.fromString(market.program||SETTLEMENT_PROGRAM), pool=PublicKey.fromString(market.pool.pool), vault=PublicKey.fromString(market.pool.vault), lpMint=PublicKey.fromString(market.pool.lpMint); const b=await builder(wallet);
  const token=await ensureTokenAccount(wallet,mint,b); const lp=await ensureTokenAccount(wallet,lpMint,b,market.pool.creatorLp); const [authority]=PublicKey.findProgramAddress(['pool_authority',pool.toBytes()],programId);
  const adding=side==='add'; const data=adding?encodeAddLiquidity({rloIn:rloAmount,tokensIn:tokenAmount,minLpOut:minOut}):encodeRemoveLiquidity({lpIn:lpAmount,minRloOut:rloAmount,minTokensOut:tokenAmount});
  b.addInstruction({programId,accounts:[{pubkey:pool,isSigner:false,isWritable:true},{pubkey:wallet,isSigner:true,isWritable:true},{pubkey:mint,isSigner:false,isWritable:false},{pubkey:token.address,isSigner:false,isWritable:true},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:lpMint,isSigner:false,isWritable:true},{pubkey:lp.address,isSigner:false,isWritable:true},{pubkey:authority,isSigner:false,isWritable:false},{pubkey:tokenProgram,isSigner:false,isWritable:false},{pubkey:systemProgram,isSigner:false,isWritable:false}],data});
  const signers=[token.signer,lp.signer].filter(Boolean); const signature=await walletSend(wallet,b.build(),{title:`${adding?'Add':'Remove'} ${market.ticker} liquidity`,detail:'RialoFun DEX pool liquidity transaction'},signers); signers.forEach(key=>key.dispose());return{signature};
}
export async function readOnchainMarket(market,walletAddress){
  const decode=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0)); const state=await client.getAccountInfo(PublicKey.fromString(market.state)),d=decode(state.data[0]); const read=(bytes,o,size)=>{let n=0n;for(let i=o+size-1;i>=o;i--)n=(n<<8n)|BigInt(bytes[i]);return n}; const u128=o=>read(d,o,16); let balance=0n; const saved=walletAddress&&localStorage.getItem(storageKey(walletAddress,market.mint)); const tokenAddress=saved||market.tokenAccount;
  if(tokenAddress)try{const a=await client.getAccountInfo(PublicKey.fromString(tokenAddress));balance=read(decode(a.data[0]),64,8)}catch{}
  return{phase:d[3]===1?'pool':'curve',virtualRlo:Number(u128(40))/1e9,tokenReserve:Number(u128(56))/1e6,sold:Number(u128(72))/1e6,actualRlo:Number(u128(88))/1e9,fees:Number(u128(104))/1e9,balance:Number(balance)/1e6,tokenAccount:tokenAddress};
}
export async function getRloBalance(address){return Number(await client.getBalance(PublicKey.fromString(address)))/1e9}
